version: '3.5'

services:

### Jenkins ###################################################
  jenkins:
    build: ./jenkins
    environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
    ports:product_list
      - "${JENKINS_HOST_SLAVE_AGENT_PORT}:50000"
      - "${JENKINS_HOST_HTTP_PORT}:8080"
    privileged: true
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - backend
